[package]
name = "monte-carlo-strategies-in-scientific-computing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linfa = "0.6.0"
polars = "0.22.8"
nalgebra = "0.31.0"
plotters = "0.3.1"
